baseURL = "https://upflow-eu.github.io/"
languageCode = "en"
title = "UPFLOW"
theme = "ananke"
SectionPagesMenu = "main"
enableGitInfo = "true"
Copyright = "UPFLOW - All rights reserved,"

[params]
site_logo = "/logo_UP1-1.png"
twitter = "https://twitter.com/upfloweu"
instagram = ""
youtube = ""
github = "https://github.com/upflow-eu"
