baseURL = "https://upflow-eu.github.io/"
languageCode = "en"
title = "UPFLOW"
theme = "ananke"
SectionPagesMenu = "main"
enableGitInfo = "true"
Copyright = "UPFLOW - All rights reserved,"

[params]
site_logo = "/logo_UP1-1.png"
twitter = "https://twitter.com/upfloweu"
instagram = "https://www.instagram.com/upfloweu/"
youtube = "https://www.youtube.com/channel/UCa3wuhPfmAeYsNd73rSI8gA/about"
github = "https://github.com/upflow-eu"
custom_css = ["css/custom.css"]
